services:

  qdrant-cloud:
    image: qdrant/qdrant:latest
    container_name: qdrant-cloud
    ports:
      - "6335:6333"
      - "6336:6334"
    volumes:
      - ./data/qdrant_cloud_storage:/qdrant/storage
    restart: unless-stopped